#pragma once

/*
 * Bounds for values received from an eUICC or an RSP server.  Values with an
 * ASN.1 SIZE constraint mirror SGP.22.  The remaining limits are deliberately
 * generous interoperability ceilings that prevent a malformed 16 MiB command
 * response from becoming an equally large Java/UI object.
 */
#define EUICC_RSP_ICCID_BYTES 10U
#define EUICC_RSP_EID_BYTES 16U
#define EUICC_RSP_AID_MIN_BYTES 1U
#define EUICC_RSP_AID_MAX_BYTES 16U

#define EUICC_RSP_PROFILE_NICKNAME_CHARS 64U
#define EUICC_RSP_PROVIDER_NAME_CHARS 32U
#define EUICC_RSP_PROFILE_NAME_CHARS 64U
#define EUICC_RSP_ICON_BYTES 1024U
#define EUICC_RSP_SAS_NUMBER_CHARS 64U

#define EUICC_RSP_FQDN_BYTES 253U
#define EUICC_RSP_GID_BYTES 255U
#define EUICC_RSP_DP_PROPRIETARY_BYTES 128U
#define EUICC_RSP_BIT_STRING_BYTES 64U
#define EUICC_RSP_CARD_RESOURCE_BYTES 1024U
#define EUICC_RSP_EUICC_INFO_BYTES (16U * 1024U)

#define EUICC_RSP_CI_PKID_BYTES 64U
#define EUICC_RSP_CI_PKID_COUNT 128U
#define EUICC_RSP_PROFILE_COUNT 128U
#define EUICC_RSP_NOTIFICATION_COUNT 128U
#define EUICC_RSP_NOTIFICATION_CONFIG_BYTES 4096U

#define EUICC_RSP_PLATFORM_LABEL_CHARS 256U
#define EUICC_RSP_DISCOVERY_URL_CHARS 2048U
#define EUICC_RSP_CERTIFICATION_DATA_BYTES (16U * 1024U)

/* StoreMetadata is normally only a few KiB, even with its maximum-size icon. */
#define EUICC_RSP_METADATA_BASE64_BYTES (64U * 1024U)
#define EUICC_RSP_SIGNED_DATA_BASE64_BYTES (64U * 1024U)
#define EUICC_RSP_SIGNATURE_BASE64_BYTES (16U * 1024U)
#define EUICC_RSP_CERTIFICATE_BASE64_BYTES (96U * 1024U)
#define EUICC_RSP_PKID_BASE64_BYTES 256U
#define EUICC_RSP_BOUND_PROFILE_PACKAGE_BASE64_BYTES (48U * 1024U * 1024U)
