package net.typeblog.lpac_jni.impl

import java.net.URL

/** Accepts only the fixed ES9+/ES11 request surface generated by libeuicc. */
internal fun validateRspRequestUrl(value: String): URL {
    require(value.length <= MaximumRspUrlCharacters) { "RSP request URL is too long" }
    val parsed = URL(value)
    require(parsed.protocol == "https") { "SM-DP+ servers must use the HTTPS protocol" }
    require(parsed.host.isNotBlank() && parsed.userInfo == null) {
        "RSP request URL has an invalid authority"
    }
    require(parsed.query == null && parsed.ref == null && parsed.path in AllowedRspPaths) {
        "RSP request URL has an unexpected path or parameters"
    }
    return parsed
}

private const val MaximumRspUrlCharacters = 4_096
private val AllowedRspPaths = setOf(
    "/gsma/rsp2/es9plus/initiateAuthentication",
    "/gsma/rsp2/es9plus/authenticateClient",
    "/gsma/rsp2/es9plus/getBoundProfilePackage",
    "/gsma/rsp2/es9plus/cancelSession",
    "/gsma/rsp2/es9plus/handleNotification",
)
